[package]
name = "shiguredo_rowan"
version = "2026.0.0"
edition = "2024"
rust-version = "1.88.0"
description = "Library for generic lossless syntax trees"
repository = "https://github.com/shiguredo/rowan"
license = "Apache-2.0"
include = ["/LICENSE", "/README.md", "/src/**/*"]

[dependencies]
hashbrown = {
  version = "0.17.1",
  default-features = false,
  features = [
    "inline-more",
    "raw-entry",
  ]
}
rustc-hash = "2.1.2"
text-size = "1.1.1"
